#!/usr/bin/env python3
"""
fleet_batch_sim.py — Generate YAML configs for top fleet commodities
and batch-run them through the TankerTransferV2 simulation.

Standard rig assumptions:
  - Tank: T5183 (75" diameter, 30.5 ft barrel, 7000 gal)
  - Air supply: 40 SCFM (typical compressor)
  - No pre-pressurization (0 psig — confirmed best by sweep data)
  - 1 pipe segment: 3" valve → 3" hose 20 ft
  - Temperature: 20 °C
"""

import os
import sys

CONFIG_DIR = os.environ.get("CONFIG_DIR", "/opt/sim-lab/truck-tanker-sim-env/config")
TEMPLATE = """# Fleet Commodity Simulation — {name}
# Auto-generated by fleet_batch_sim.py

scenario_name: fleet_{safe_name}

# Tank Geometry (T5183)
tank_total_volume_gal: 7000
tank_diameter_in: 75.0
tank_length_ft: 30.5

# Initial Conditions
initial_liquid_volume_gal: {volume_gal}
initial_tank_pressure_psig: 0.0
gas_temperature_C: 20.0
ambient_pressure_psia: 14.696

# Pressure Limits
max_tank_pressure_psig: 25.0
relief_valve_pressure_psig: 27.5
relief_valve_Cd: 0.62
relief_valve_diameter_in: 1.0

# Air Supply
air_supply_scfm: 19.0

# Liquid Properties
liquid_density_kg_m3: {density_kg_m3:.1f}
liquid_viscosity_cP: {viscosity_cP}

# Outlet Valve
valve_diameter_in: 3.0
valve_K_open: 0.2
valve_opening_fraction: 1.0

# Pipe Segments (num_pipes: 1)
num_pipes: 1
pipe1_diameter_in: 3.0
pipe1_length_ft: 20.0
pipe1_roughness_mm: 0.01
pipe1_K_minor: 2.5
pipe2_diameter_in: 3.0
pipe2_length_ft: 0.0
pipe2_roughness_mm: 0.01
pipe2_K_minor: 0.0
pipe3_diameter_in: 3.0
pipe3_length_ft: 0.0
pipe3_roughness_mm: 0.01
pipe3_K_minor: 0.0
pipe4_diameter_in: 3.0
pipe4_length_ft: 0.0
pipe4_roughness_mm: 0.01
pipe4_K_minor: 0.0
pipe5_diameter_in: 3.0
pipe5_length_ft: 0.0
pipe5_roughness_mm: 0.01
pipe5_K_minor: 0.0

# Elevation & Receiver
elevation_change_ft: 0.0
receiver_pressure_psig: 0.0

# Minimum volume
min_liquid_volume_gal: 1.0

# Simulation
stop_time_s: {stop_time}
output_interval_s: 1.0
"""

# Top fleet commodities to simulate
# (name, loads, viscosity_cP, SG, max_gal)
PRODUCTS = [
    ("Ethylene Glycol",          56, 16.1,  1.113, 6500),
    ("Resin Solution",           32, 500,   1.05,  6500),
    ("Sodium Silicate",          28, 180,   1.39,  6500),
    ("Biomass",                  27, 50,    1.05,  6500),
    ("Diethylene Glycol",        27, 30.2,  1.118, 6500),
    ("DOSS 70 PG",               26, 200,   1.08,  6500),
    ("NIPOL 1411 LATEX",         26, 200,   1.0,   6500),
    ("Smartcide 1984A",          23, 5,     1.02,  6500),
    ("Transformer Oil Type II",  22, 11,    0.88,  6500),
    ("Used Motor Oil",           22, 20,    0.88,  6500),
    ("OCD",                      21, 0.6,   1.05,  6500),
    ("Triethylene Glycol",       19, 37.3,  1.125, 6500),
    ("Propylene Glycol",         17, 42,    1.036, 6500),
    ("Tall Oil Rosin",           16, 5000,  1.07,  6500),
    ("VIVATEC 500",              16, 100,   0.99,  6500),
    ("Wax Additive C24-28",      16, 5,     0.80,  6500),
    ("Kaolin Clay",              10, 300,   1.15,  6500),
    ("CRUDE GLYCERIN",            5, 934,   1.261, 6500),
    ("TEA 99",                    2, 590,   1.124, 6500),
    ("Perchloroethylene",         3, 9900,  1.622, 6500),
]


def safe_name(name):
    return name.lower().replace(" ", "_").replace("-", "_").replace("/","_").replace("(","").replace(")","")


def main():
    configs = []
    for name, loads, cP, sg, vol_gal in PRODUCTS:
        sn = safe_name(name)
        density_kg_m3 = sg * 1000.0

        # Choose stop time based on viscosity
        if cP < 50:
            stop_time = 7200    # 2 hr
        elif cP < 500:
            stop_time = 14400   # 4 hr
        elif cP < 2000:
            stop_time = 36000   # 10 hr
        else:
            stop_time = 72000   # 20 hr

        yaml_content = TEMPLATE.format(
            name=name,
            safe_name=sn,
            volume_gal=vol_gal,
            density_kg_m3=density_kg_m3,
            viscosity_cP=cP,
            stop_time=stop_time,
        )

        yaml_path = os.path.join(CONFIG_DIR, f"fleet_{sn}.yaml")
        with open(yaml_path, "w") as f:
            f.write(yaml_content)

        configs.append((name, loads, cP, sg, vol_gal, yaml_path))
        print(f"  Created: {yaml_path}")

    # Write a manifest
    manifest_path = os.path.join(CONFIG_DIR, "fleet_batch_manifest.txt")
    with open(manifest_path, "w") as f:
        for name, loads, cP, sg, vol, yp in configs:
            f.write(f"{os.path.basename(yp)}|{name}|{loads}|{cP}|{sg}|{vol}\n")
    print(f"\nManifest: {manifest_path}")
    print(f"Total configs: {len(configs)}")

    return configs


if __name__ == "__main__":
    main()
