#!/usr/bin/env python3
"""
six_studies_gen.py — Generate YAML configs for all 6 simulation studies.

Studies:
  1. Compressor Sizing   — SCFM sweep for failing products (Tall Oil Rosin, Perchloroethylene)
  2. Hose Upgrade        — 3" vs 4" hose for all 20 products
  3. Break-Even Viscosity — Binary search: find exact cP cutoff at current equipment
  4. Equipment Combos     — SCFM × hose × valve matrix for failing products
  5. Partial Loads        — Volume sweep for key products
  6. Elevation/Backpressure — Site condition sweep for representative products

All configs go to config/studies/ with study-prefixed names.
"""

import os

CONFIG_DIR = os.environ.get("CONFIG_DIR", "/opt/sim-lab/truck-tanker-sim-env/config/studies")
os.makedirs(CONFIG_DIR, exist_ok=True)

# ── Base template ──
TEMPLATE = """# {study_label}
# Auto-generated by six_studies_gen.py

scenario_name: {scenario_name}

# Tank Geometry (T5183)
tank_total_volume_gal: 7000
tank_diameter_in: 75.0
tank_length_ft: 30.5

# Initial Conditions
initial_liquid_volume_gal: {volume_gal}
initial_tank_pressure_psig: 0.0
gas_temperature_C: 20.0
ambient_pressure_psia: 14.696

# Pressure Limits
max_tank_pressure_psig: 25.0
relief_valve_pressure_psig: 27.5
relief_valve_Cd: 0.62
relief_valve_diameter_in: 1.0

# Air Supply
air_supply_scfm: {scfm}
compressor_clearance: {clearance}

# Liquid Properties
liquid_density_kg_m3: {density:.1f}
liquid_viscosity_cP: {viscosity}

# Outlet Valve
valve_diameter_in: {valve_dia}
valve_K_open: 0.2
valve_opening_fraction: {valve_opening}

# Pipe Segments
num_pipes: 1
pipe1_diameter_in: {hose_dia}
pipe1_length_ft: {hose_length}
pipe1_roughness_mm: 0.01
pipe1_K_minor: 2.5
pipe2_diameter_in: 3.0
pipe2_length_ft: 0.0
pipe2_roughness_mm: 0.01
pipe2_K_minor: 0.0
pipe3_diameter_in: 3.0
pipe3_length_ft: 0.0
pipe3_roughness_mm: 0.01
pipe3_K_minor: 0.0
pipe4_diameter_in: 3.0
pipe4_length_ft: 0.0
pipe4_roughness_mm: 0.01
pipe4_K_minor: 0.0
pipe5_diameter_in: 3.0
pipe5_length_ft: 0.0
pipe5_roughness_mm: 0.01
pipe5_K_minor: 0.0

# Elevation & Receiver
elevation_change_ft: {elevation}
receiver_pressure_psig: {receiver_psig}

# Minimum volume
min_liquid_volume_gal: 1.0

# Simulation
stop_time_s: {stop_time}
output_interval_s: 1.0
"""

def safe(name):
    return name.lower().replace(" ", "_").replace("-", "_").replace("/", "_").replace("(", "").replace(")", "")

def stop_time_for(cP, extra_factor=1.0):
    """Choose simulation stop time based on viscosity."""
    if cP < 50:
        base = 7200
    elif cP < 500:
        base = 14400
    elif cP < 2000:
        base = 36000
    else:
        base = 72000
    return int(base * extra_factor)

def write_config(scenario_name, study_label, volume_gal=6500, scfm=19,
                 clearance=0.0, density=1000.0, viscosity=1.0,
                 valve_dia=3.0, valve_opening=1.0,
                 hose_dia=3.0, hose_length=20.0,
                 elevation=0.0, receiver_psig=0.0, stop_time=7200):
    content = TEMPLATE.format(
        study_label=study_label,
        scenario_name=scenario_name,
        volume_gal=volume_gal,
        scfm=scfm,
        clearance=clearance,
        density=density,
        viscosity=viscosity,
        valve_dia=valve_dia,
        valve_opening=valve_opening,
        hose_dia=hose_dia,
        hose_length=hose_length,
        elevation=elevation,
        receiver_psig=receiver_psig,
        stop_time=stop_time,
    )
    path = os.path.join(CONFIG_DIR, f"{scenario_name}.yaml")
    with open(path, "w") as f:
        f.write(content)
    return path

# ── Product definitions ──
FAILING_PRODUCTS = [
    ("Tall Oil Rosin",      5000, 1.07),
    ("Perchloroethylene",   9900, 1.622),
]

ALL_PRODUCTS = [
    ("Ethylene Glycol",        16.1,  1.113),
    ("Resin Solution",         500,   1.05),
    ("Sodium Silicate",        180,   1.39),
    ("Biomass",                50,    1.05),
    ("Diethylene Glycol",      30.2,  1.118),
    ("DOSS 70 PG",             200,   1.08),
    ("NIPOL 1411 LATEX",       200,   1.0),
    ("Smartcide 1984A",        5,     1.02),
    ("Transformer Oil Type II",11,    0.88),
    ("Used Motor Oil",         20,    0.88),
    ("OCD",                    0.6,   1.05),
    ("Triethylene Glycol",     37.3,  1.125),
    ("Propylene Glycol",       42,    1.036),
    ("Tall Oil Rosin",         5000,  1.07),
    ("VIVATEC 500",            100,   0.99),
    ("Wax Additive C24-28",    5,     0.80),
    ("Kaolin Clay",            300,   1.15),
    ("CRUDE GLYCERIN",         934,   1.261),
    ("TEA 99",                 590,   1.124),
    ("Perchloroethylene",      9900,  1.622),
]

# Representative sample for studies 5 & 6 (low/med/high viscosity)
REPRESENTATIVE = [
    ("OCD",                0.6,   1.05),    # water-like
    ("Ethylene Glycol",    16.1,  1.113),   # light
    ("Biomass",            50,    1.05),     # medium-light
    ("DOSS 70 PG",         200,   1.08),    # medium
    ("Resin Solution",     500,   1.05),    # heavy 
    ("CRUDE GLYCERIN",     934,   1.261),   # very heavy (border)
    ("Tall Oil Rosin",     5000,  1.07),    # nightmare
    ("Perchloroethylene",  9900,  1.622),   # worst
]

all_configs = []  # (study, scenario_name, yaml_path, metadata_dict)

# =============================================================================
# STUDY 1: Compressor Sizing — SCFM sweep for failing products
# =============================================================================
print("=" * 60)
print("STUDY 1: Compressor Sizing — SCFM sweep for failing products")
print("=" * 60)

SCFM_SWEEP = [19, 25, 30, 40, 50, 75, 100]
# Also include compressor types: plant air (c=0), PTO (c=0.02), portable (c=0.04)
COMP_TYPES = [
    ("plant", 0.0),
    ("pto",   0.02),
]

for name, cP, sg in FAILING_PRODUCTS:
    sn = safe(name)
    for scfm in SCFM_SWEEP:
        for comp_label, clearance in COMP_TYPES:
            scenario = f"s1_{sn}_{scfm}scfm_{comp_label}"
            label = f"Study 1: {name} @ {scfm} SCFM ({comp_label})"
            path = write_config(
                scenario_name=scenario,
                study_label=label,
                density=sg * 1000,
                viscosity=cP,
                scfm=scfm,
                clearance=clearance,
                stop_time=stop_time_for(cP),
            )
            all_configs.append(("study1", scenario, path, {
                "product": name, "cP": cP, "sg": sg,
                "scfm": scfm, "comp_type": comp_label,
            }))
            print(f"  {scenario}")

# =============================================================================
# STUDY 2: Hose Upgrade — 3" vs 4" hose for all 20 products
# =============================================================================
print(f"\n{'=' * 60}")
print("STUDY 2: Hose Upgrade — 3\" vs 4\" hose for all 20 products")
print("=" * 60)

HOSE_SIZES = [3.0, 4.0]

for name, cP, sg in ALL_PRODUCTS:
    sn = safe(name)
    for hose in HOSE_SIZES:
        h_label = f"{hose:.0f}in"
        scenario = f"s2_{sn}_hose{h_label}"
        # valve matches hose size
        valve = hose
        label = f"Study 2: {name} — {h_label} hose"
        path = write_config(
            scenario_name=scenario,
            study_label=label,
            density=sg * 1000,
            viscosity=cP,
            valve_dia=valve,
            hose_dia=hose,
            stop_time=stop_time_for(cP),
        )
        all_configs.append(("study2", scenario, path, {
            "product": name, "cP": cP, "sg": sg,
            "hose_in": hose, "valve_in": valve,
        }))
        print(f"  {scenario}")

# =============================================================================
# STUDY 3: Break-Even Viscosity — fine sweep around 934-5000 cP
# =============================================================================
print(f"\n{'=' * 60}")
print("STUDY 3: Break-Even Viscosity — sweep 500-5000 cP range")
print("=" * 60)

# We know 934 cP passes, 5000 cP fails. Sweep densely in between.
VISC_SWEEP = [500, 750, 1000, 1250, 1500, 1750, 2000, 2500, 3000, 3500, 4000, 4500, 5000]
# Use SG=1.1 (generic mid-range)
BREAK_SG = 1.1

for cP in VISC_SWEEP:
    scenario = f"s3_breakeven_{cP}cP"
    label = f"Study 3: Break-Even — {cP} cP (SG={BREAK_SG})"
    path = write_config(
        scenario_name=scenario,
        study_label=label,
        density=BREAK_SG * 1000,
        viscosity=cP,
        stop_time=stop_time_for(cP, extra_factor=1.5),
    )
    all_configs.append(("study3", scenario, path, {
        "product": f"Generic {cP}cP", "cP": cP, "sg": BREAK_SG,
    }))
    print(f"  {scenario}")

# =============================================================================
# STUDY 4: Equipment Combo Optimizer — SCFM × hose × valve for failing products
# =============================================================================
print(f"\n{'=' * 60}")
print("STUDY 4: Equipment Combo Optimizer")
print("=" * 60)

S4_SCFM = [19, 30, 50]
S4_HOSE = [3.0, 4.0]
S4_VALVE = [3.0, 4.0]

for name, cP, sg in FAILING_PRODUCTS:
    sn = safe(name)
    for scfm in S4_SCFM:
        for hose in S4_HOSE:
            for valve in S4_VALVE:
                # Skip combos where valve > hose (unusual)
                if valve > hose:
                    continue
                h = f"{hose:.0f}"
                v = f"{valve:.0f}"
                scenario = f"s4_{sn}_{scfm}scfm_h{h}_v{v}"
                label = f"Study 4: {name} — {scfm}SCFM, {h}\"hose, {v}\"valve"
                path = write_config(
                    scenario_name=scenario,
                    study_label=label,
                    density=sg * 1000,
                    viscosity=cP,
                    scfm=scfm,
                    valve_dia=valve,
                    hose_dia=hose,
                    stop_time=stop_time_for(cP),
                )
                all_configs.append(("study4", scenario, path, {
                    "product": name, "cP": cP, "sg": sg,
                    "scfm": scfm, "hose_in": hose, "valve_in": valve,
                }))
                print(f"  {scenario}")

# =============================================================================
# STUDY 5: Partial Loads — Volume sweep for representative products
# =============================================================================
print(f"\n{'=' * 60}")
print("STUDY 5: Partial Loads")
print("=" * 60)

VOLUMES = [2000, 3000, 4000, 5000, 6500]

for name, cP, sg in REPRESENTATIVE:
    sn = safe(name)
    for vol in VOLUMES:
        scenario = f"s5_{sn}_{vol}gal"
        label = f"Study 5: {name} — {vol} gal"
        path = write_config(
            scenario_name=scenario,
            study_label=label,
            volume_gal=vol,
            density=sg * 1000,
            viscosity=cP,
            stop_time=stop_time_for(cP),
        )
        all_configs.append(("study5", scenario, path, {
            "product": name, "cP": cP, "sg": sg, "volume_gal": vol,
        }))
        print(f"  {scenario}")

# =============================================================================
# STUDY 6: Elevation + Back-pressure — site condition sweep
# =============================================================================
print(f"\n{'=' * 60}")
print("STUDY 6: Elevation + Back-pressure")
print("=" * 60)

ELEVATIONS = [0, 5, 10, 15, 20]       # ft uphill
BACK_PRESSURES = [0, 5, 10]            # psig receiver

for name, cP, sg in REPRESENTATIVE:
    sn = safe(name)
    for elev in ELEVATIONS:
        for bp in BACK_PRESSURES:
            # Skip (0,0) — already have that from baseline
            if elev == 0 and bp == 0:
                continue
            scenario = f"s6_{sn}_elev{elev}ft_bp{bp}psi"
            label = f"Study 6: {name} — {elev}ft up, {bp}psig back"
            path = write_config(
                scenario_name=scenario,
                study_label=label,
                density=sg * 1000,
                viscosity=cP,
                elevation=elev,
                receiver_psig=bp,
                stop_time=stop_time_for(cP, extra_factor=1.5),
            )
            all_configs.append(("study6", scenario, path, {
                "product": name, "cP": cP, "sg": sg,
                "elevation_ft": elev, "backpressure_psig": bp,
            }))
            print(f"  {scenario}")

# =============================================================================
# Write master manifest
# =============================================================================
manifest_path = os.path.join(CONFIG_DIR, "studies_manifest.txt")
with open(manifest_path, "w") as f:
    for study, scenario, path, meta in all_configs:
        # study|scenario_name|yaml_file|key=val,key=val,...
        meta_str = ",".join(f"{k}={v}" for k, v in meta.items())
        f.write(f"{study}|{scenario}|{os.path.basename(path)}|{meta_str}\n")

print(f"\n{'=' * 60}")
print(f"TOTAL CONFIGS GENERATED: {len(all_configs)}")
print(f"  Study 1 (Compressor Sizing):   {sum(1 for s,_,_,_ in all_configs if s=='study1')}")
print(f"  Study 2 (Hose Upgrade):        {sum(1 for s,_,_,_ in all_configs if s=='study2')}")
print(f"  Study 3 (Break-Even Visc):     {sum(1 for s,_,_,_ in all_configs if s=='study3')}")
print(f"  Study 4 (Equipment Combos):    {sum(1 for s,_,_,_ in all_configs if s=='study4')}")
print(f"  Study 5 (Partial Loads):       {sum(1 for s,_,_,_ in all_configs if s=='study5')}")
print(f"  Study 6 (Elevation/BP):        {sum(1 for s,_,_,_ in all_configs if s=='study6')}")
print(f"\nManifest: {manifest_path}")
